// GENERATED by extract-image-provider.mjs — do not edit.
//
// Imports are added here because the extracted functions reference them and the
// C++ raw string they came from does not carry them. Omitting these makes
// currentMiaoDeskBaseUrl swallow a ReferenceError in its catch and return "", which
// looks exactly like "no profile configured" — a silent failure that reads as a
// product bug.
import { readFile } from "node:fs/promises";
import { join } from "node:path";

const IMAGE_PROVIDER = (process.env.MIAODESK_IMAGE_PROVIDER ?? "").trim();
const IMAGE_MODEL = (process.env.MIAODESK_IMAGE_MODEL ?? "").trim();
// A loopback endpoint is the product's own local inference server, which the
// profile already treats as keyless. Treating it as keyless here too is what makes
// "run everything locally" work without inventing a token.
const LOOPBACK_HOSTS = ["127.0.0.1", "localhost", "[::1]", "::1"];
function isLoopback(baseUrl) { return LOOPBACK_HOSTS.some((h) => baseUrl.includes(h)); }

async function currentMiaoDeskBaseUrl(): Promise<string> {
  const agentDir = process.env.PI_CODING_AGENT_DIR;
  if (!agentDir) return "";
  try {
    const raw = await readFile(join(agentDir, "models.json"), "utf8");
    return String(JSON.parse(raw)?.providers?.miaodesk?.baseUrl ?? "");
  } catch { return ""; }
}


// Resolves the credential for the configured image provider.
//
// The old rule was "reuse the main key only when baseUrl contains openrouter.ai",
// which made image generation impossible the moment baseUrl pointed at a local
// inference server. The new rules:
//   * an explicit provider-specific env var wins;
//   * a loopback endpoint is keyless, matching how the profile itself treats it;
//   * otherwise reuse the main model key, whatever the provider is.
async function resolveImageApiKey(): Promise<string> {
  const explicit = process.env.MIAODESK_IMAGE_API_KEY?.trim();
  if (explicit) return explicit;
  if (!IMAGE_PROVIDER) return "";
  const baseUrl = (await currentMiaoDeskBaseUrl()).toLowerCase();
  if (isLoopback(baseUrl)) return "local";
  return process.env.MIAODESK_MODEL_API_KEY?.trim() ?? "";
}


async function generateImage(prompt: string, fileName: string, signal?: AbortSignal): Promise<string> {
  if (!IMAGE_PROVIDER) {
    throw new Error("图片生成能力未配置：API Profile 未指定图片 Provider。聊天和其他 Pi 工具仍可正常使用。");
  }
  const imageModel = IMAGE_MODEL || DEFAULT_IMAGE_MODEL;
  const apiKey = await resolveImageApiKey();
  if (!apiKey) throw new Error(`图片生成能力当前未配置：需要 ${IMAGE_PROVIDER} 的 API Key。聊天和其他 Pi 工具仍可正常使用。`);
  console.error(`[MiaoDesk][artifact] image_generate start provider=${IMAGE_PROVIDER} model=${imageModel}`);
  const { getImageModel } = await import("./stub-get-image-model.mjs");
  const model = getImageModel(IMAGE_PROVIDER, imageModel);
  if (!model) throw new Error(`Pi 图片模型不可用：${IMAGE_PROVIDER}/${imageModel}`);
  throw new Error("STUB: provider/model decision reached, real HTTP not exercised");
}

const DEFAULT_IMAGE_MODEL = "google/gemini-2.5-flash-image";
export { currentMiaoDeskBaseUrl, resolveImageApiKey, generateImage,
         IMAGE_PROVIDER, IMAGE_MODEL, DEFAULT_IMAGE_MODEL, isLoopback };
