#!/usr/bin/env python3
"""Generate the missing artwork for NeonCity.mdwall and MysticMoon.mdwall.

Why this exists, and why it is not "inventing the visuals"
----------------------------------------------------------
Both packages declare five image layers in scene.ini, each with a filename, a
placement, an opacity and an animation. Neither package has ever contained those
files: git has no record of them and the names appear nowhere else in the tree.
The consequence is not "the art looks wrong" — it is that `DrawLayer` starts with
`if (!layer.bitmap) return;`, so every layer is skipped and the wallpaper draws
nothing at all, silently. That is the same silent failure the content rules exist
to prevent, and no amount of renderer work closes it.

So the composition was never the open question. `scene.ini` already decides it:
five layers, back to front, at named boxes and opacities. What is missing is the
pixel content of five files, and this script produces it.

What that means, stated plainly so nobody has to reverse-engineer it later:

  * The **composition** is scene.ini's. Layer order, boxes, opacities, animation
    parameters and the fact that a layer is a skyline rather than a portrait all
    come from the .ini; nothing here reinterprets them.
  * The **pixels** are synthetic. A human art pass can replace any file with real
    art and nothing else changes — scene.json references these files by name, and
    the renderer scales each bitmap to the layer box.
  * Everything is **seeded per package and per layer**, so regenerating produces
    byte-identical output. That is what makes this a reviewed, reproducible input
    rather than a one-off drop: `--check` re-renders and compares checksums.
  * No third-party material is involved, which matters for the asset-licence
    question (P0-5): these are generated by the project itself.

Output sizes are each layer's own box from scene.ini, so the renderer's
scale-to-rect is a no-op and the art is never resampled.

Run:  python3 scripts/generate-builtin-wallpaper-art.py [--write] [--check]
"""
import argparse
import hashlib
import io
import math
import pathlib
import random
import struct
import sys
import zlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
WALLPAPERS = ROOT / "assets" / "wallpapers"


# ---------------------------------------------------------------------------
# PNG output (stdlib only)
# ---------------------------------------------------------------------------
def write_png(path, width, height, rgba):
    """Write an 8-bit RGBA PNG. Straight alpha, no interlacing."""
    raw = bytearray()
    stride = width * 4
    for y in range(height):
        raw.append(0)  # filter type 0: None. Per-row filters would buy a few
        # percent on gradients and cost a real dependency; zlib already handles
        # the long runs these images are made of.
        raw += rgba[y * stride:(y + 1) * stride]
    compressed = zlib.compress(bytes(raw), 9)

    def chunk(tag, data):
        return (struct.pack(">I", len(data)) + tag + data +
                struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))

    header = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)
    blob = (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", header) +
            chunk(b"IDAT", compressed) + chunk(b"IEND", b""))
    path.write_bytes(blob)


def write_jpeg(path, width, height, rgb, quality=88):
    """Encode an 8-bit RGB JPEG.

    PIL when it is installed, otherwise `sips` on macOS. Neither is a gate
    dependency — this is a content-generation tool a human runs, and the image it
    writes is committed. The output is verified below by decoding it again, so a
    converter that silently produced something else cannot pass unnoticed.
    """
    try:
        from PIL import Image  # type: ignore
        image = Image.frombytes("RGB", (width, height), bytes(rgb))
        image.save(path, "JPEG", quality=quality, subsampling=0, optimize=True)
        return "PIL"
    except ImportError:
        pass
    png = path.with_suffix(".tmp.png")
    write_png(png, width, height, _rgb_to_rgba(rgb))
    import subprocess
    result = subprocess.run(
        ["sips", "-s", "format", "jpeg", "-s", "formatOptions", str(quality),
         str(png), "--out", str(path)],
        capture_output=True, text=True)
    png.unlink(missing_ok=True)
    if result.returncode != 0 or not path.exists():
        raise SystemExit(
            "❌ 写不出 JPEG:既没有 PIL,macosOS 的 sips 也失败了。\n%s" % result.stderr)
    return "sips"


def _rgb_to_rgba(rgb):
    rgba = bytearray(len(rgb) // 3 * 4)
    for i in range(len(rgb) // 3):
        rgba[i * 4:i * 4 + 3] = rgb[i * 3:i * 3 + 3]
        rgba[i * 4 + 3] = 0xFF
    return rgba


def read_png_size(path):
    data = path.read_bytes()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        return None
    w, h = struct.unpack(">II", data[16:24])
    return w, h


def read_jpeg_size(path):
    data = path.read_bytes()
    i = 2
    while i < len(data) - 9:
        if data[i] != 0xFF:
            i += 1
            continue
        marker = data[i + 1]
        if marker in (0xD8, 0xD9) or 0xD0 <= marker <= 0xD7:
            i += 2
            continue
        if marker in (0xC0, 0xC1, 0xC2, 0xC3):
            h, w = struct.unpack(">HH", data[i + 5:i + 9])
            return w, h
        length = struct.unpack(">H", data[i + 2:i + 4])[0]
        i += 2 + length
    return None


# ---------------------------------------------------------------------------
# A small straight-alpha raster surface
# ---------------------------------------------------------------------------
class Surface:
    def __init__(self, width, height):
        self.width = width
        self.height = height
        self.px = bytearray(width * height * 4)  # transparent black

    def blend(self, x, y, r, g, b, a):
        """Source-over one pixel, a in 0..255."""
        if x < 0 or y < 0 or x >= self.width or y >= self.height:
            return
        i = (y * self.width + x) * 4
        if a <= 0:
            return
        if a >= 255:
            self.px[i:i + 4] = bytes((int(r), int(g), int(b), 255))
            return
        sa = a / 255.0
        da = self.px[i + 3] / 255.0
        out_a = sa + da * (1 - sa)
        if out_a <= 0:
            return
        for c, value in enumerate((r, g, b)):
            src = value / 255.0
            dst = self.px[i + c] / 255.0
            self.px[i + c] = int(round(255 * (src * sa + dst * da * (1 - sa)) / out_a))
        self.px[i + 3] = int(round(255 * out_a))

    def fill_gradient(self, top, bottom):
        # One slice assignment per row. The per-pixel version of this was the
        # difference between a few seconds and a few minutes on a 1672x941 image,
        # and it is the kind of thing nobody notices until they regenerate.
        for y in range(self.height):
            t = y / max(1, self.height - 1)
            colour = bytes(int(round(top[c] + (bottom[c] - top[c]) * t)) for c in range(3))
            row = colour + b"\xff"
            base = y * self.width * 4
            self.px[base:base + self.width * 4] = row * self.width

    def radial(self, cx, cy, radius, colour, strength):
        """Add a soft additive halo. Ignored where it is fully transparent."""
        x0, x1 = max(0, int(cx - radius)), min(self.width, int(cx + radius) + 1)
        y0, y1 = max(0, int(cy - radius)), min(self.height, int(cy + radius) + 1)
        for y in range(y0, y1):
            dy = (y + 0.5 - cy) / radius
            for x in range(x0, x1):
                dx = (x + 0.5 - cx) / radius
                d2 = dx * dx + dy * dy
                if d2 >= 1.0:
                    continue
                falloff = (1.0 - d2) ** 2
                i = (y * self.width + x) * 4
                for c in range(3):
                    self.px[i + c] = min(255, int(self.px[i + c] + colour[c] * falloff * strength))

    def bloom(self, scale=6, strength=0.55):
        """Cheap glow: box-blur a downsampled copy and add it back.

        The alternative — a halo per light source — is O(lights x pixels) and
        these images have hundreds of windows. Downsample + blur + upsample is
        how every cheap bloom works and it is visually indistinguishable here.
        """
        w, h = self.width // scale, self.height // scale
        if w < 2 or h < 2:
            return
        stride = self.width * 4
        small = [[[0.0, 0.0, 0.0] for _ in range(w)] for _ in range(h)]
        for y in range(h):
            for x in range(w):
                acc = [0.0, 0.0, 0.0]
                for sy in range(scale):
                    for sx in range(scale):
                        i = ((y * scale + sy) * self.width + (x * scale + sx)) * 4
                        if self.px[i + 3] < 8:
                            continue
                        for c in range(3):
                            acc[c] += self.px[i + c]
                n = scale * scale
                for c in range(3):
                    small[y][x][c] = acc[c] / n
        blurred = _box_blur(small, w, h, 2)
        for y in range(h):
            for x in range(w):
                bx, by = x * scale, y * scale
                for sy in range(scale):
                    for sx in range(scale):
                        px, py = bx + sx, by + sy
                        if px >= self.width or py >= self.height:
                            continue
                        i = (py * self.width + px) * 4
                        # Bilinear between the blurred samples: nearest-neighbour
                        # upsampling makes the glow visibly blocky at this size.
                        fx = (px - bx) / scale
                        fy = (py - by) / scale
                        sample = _bilinear(blurred, w, h, x + fx, y + fy)
                        for c in range(3):
                            self.px[i + c] = min(
                                255, int(self.px[i + c] + sample[c] * strength))
        del stride

    def to_rgb(self):
        """Flatten to opaque RGB — what a JPEG background needs."""
        out = bytearray(self.width * self.height * 3)
        for i in range(self.width * self.height):
            a = self.px[i * 4 + 3]
            if a >= 255:
                out[i * 3:i * 3 + 3] = self.px[i * 4:i * 4 + 3]
            elif a == 0:
                out[i * 3:i * 3 + 3] = b"\x00\x00\x00"
            else:
                for c in range(3):
                    out[i * 3 + c] = int(self.px[i * 4 + c] * a / 255)
        return out


def _box_blur(grid, w, h, radius):
    out = [[list(grid[y][x]) for x in range(w)] for y in range(h)]
    for _ in range(radius):
        tmp = [[[0.0, 0.0, 0.0] for _ in range(w)] for y in range(h)]
        for y in range(h):
            for x in range(w):
                acc = [0.0, 0.0, 0.0]
                for dy in (-1, 0, 1):
                    for dx in (-1, 0, 1):
                        xx, yy = min(w - 1, max(0, x + dx)), min(h - 1, max(0, y + dy))
                        for c in range(3):
                            acc[c] += grid[y][x][c] if False else out[yy][xx][c]
                for c in range(3):
                    tmp[y][x][c] = acc[c] / 9.0
        out = tmp
    return out


def _bilinear(grid, w, h, x, y):
    x = min(max(x, 0.0), w - 1.001)
    y = min(max(y, 0.0), h - 1.001)
    x0, y0 = int(x), int(y)
    fx, fy = x - x0, y - y0
    result = [0.0, 0.0, 0.0]
    for c in range(3):
        top = grid[y0][x0][c] * (1 - fx) + grid[y0][x0 + 1][c] * fx
        bottom = grid[y0 + 1][x0][c] * (1 - fx) + grid[y0 + 1][x0 + 1][c] * fx
        result[c] = top * (1 - fy) + bottom * fy
    return result


# ---------------------------------------------------------------------------
# Layers
# ---------------------------------------------------------------------------
def skyline(surface, rng, horizon, palette, window_palette):
    """Buildings from the bottom up to `horizon`, with lit windows.

    The silhouette is deliberately near-black rather than dark blue: the neon
    already carries the colour, and a tinted silhouette muddies it. Windows are
    what the package is named for, so they get the detail budget.
    """
    surface.fill_gradient((10, 13, 28), (26, 22, 48))
    x = -rng.randint(0, 40)
    while x < surface.width:
        width = rng.randint(46, 118)
        height = rng.randint(int(horizon * 0.18), int(horizon * 0.95))
        # int() here, not at each use: `top` feeds range() in two places and a float
        # in range() is a TypeError, while a rounded int used consistently is the same
        # pixels either way.
        top = int(horizon - height)
        body = rng.choice(palette)
        for yy in range(int(top), surface.height):
            row = yy * surface.width * 4
            shade = 1.0 - (yy - int(top)) / max(1, height) * 0.25
            colour = bytes((int(body[0] * shade), int(body[1] * shade),
                            int(body[2] * shade), 255))
            x0, x1 = max(0, x), min(surface.width, x + width)
            surface.px[row + x0 * 4:row + x1 * 4] = colour * (x1 - x0)
        # Windows on a grid with random occupancy; taller buildings get more rows.
        cell_w, cell_h = 9, 13
        for wy in range(top + 8, surface.height - 6, cell_h):
            for wx in range(x + 6, x + width - 6, cell_w):
                if rng.random() > 0.42:
                    continue
                colour = rng.choice(window_palette)
                dim = rng.uniform(0.45, 1.0)
                lit = tuple(int(c * dim) for c in colour)
                for dy in range(min(5, cell_h - 4)):
                    for dx in range(min(4, cell_w - 3)):
                        surface.blend(wx + dx, wy + dy, *lit, 235)
        x += width + rng.randint(2, 10)
    surface.bloom(scale=6, strength=0.6)
    # A low warm haze so the lower buildings read as further away.
    for y in range(int(horizon * 0.82), surface.height):
        t = (y - int(horizon * 0.82)) / max(1, surface.height - int(horizon * 0.82))
        alpha = int(70 * t)
        for x2 in range(surface.width):
            surface.blend(x2, y, 90, 60, 130, alpha)


def rain(surface, rng, count, length, alpha, thickness, tint):
    """Diagonal streaks. Length and alpha are what separate near from far rain;
    count is the other half, and both are seeded so the two layers differ but
    neither drifts between regenerations."""
    for _ in range(count):
        x = rng.uniform(-length, surface.width + length)
        y = rng.uniform(-length, surface.height)
        speed = rng.uniform(0.8, 1.25)
        steps = int(length * speed)
        for s in range(steps):
            t = s / max(1, steps - 1)
            fade = math.sin(t * math.pi)  # streaks taper at both ends
            a = int(alpha * fade)
            if thickness <= 1:
                surface.blend(int(x + s * 0.22), int(y + s), *tint, a)
            else:
                for k in range(thickness):
                    surface.blend(int(x + s * 0.22) + k, int(y + s), *tint, a)


def soft_bands(surface, rng, bands, colour, alpha, y_range, height_scale):
    """Horizontal soft bands — haze over a skyline, fog over a field, shimmer on
    water. One shape, three uses, because all three are 'a wide, low, blurred
    smear' and writing three nearly identical blurs would be three chances to
    drift apart."""
    top, bottom = y_range
    for _ in range(bands):
        cy = rng.uniform(top, bottom)
        half_h = rng.uniform(*height_scale)
        for y in range(max(0, int(cy - half_h)), min(surface.height, int(cy + half_h) + 1)):
            t = (y - cy) / half_h
            vertical = max(0.0, 1.0 - t * t)
            for x in range(surface.width):
                # A slow horizontal wobble keeps the band from reading as a
                # machine-drawn rectangle.
                wobble = 0.72 + 0.28 * math.sin(x * 0.006 + cy * 0.35 + rng.random() * 0.0)
                a = int(alpha * vertical * vertical * wobble)
                surface.blend(x, y, *colour, a)


def fireflies(surface, rng, count):
    for _ in range(count):
        x = rng.uniform(0, surface.width)
        y = rng.uniform(surface.height * 0.35, surface.height * 0.97)
        radius = rng.uniform(6, 17)
        warmth = rng.uniform(0.75, 1.0)
        colour = (int(255 * warmth), int(214 * warmth), int(120 * warmth))
        surface.radial(x, y, radius, colour, rng.uniform(0.35, 1.0))
        surface.blend(int(x), int(y), 255, 246, 214, 255)


def moon(surface, cx, cy, radius):
    """Disc, craters, halo. The halo is drawn first so the disc stays crisp."""
    surface.radial(cx, cy, radius * 6.0, (150, 170, 220), 0.5)
    surface.radial(cx, cy, radius * 2.6, (200, 214, 245), 0.7)
    for y in range(int(cy - radius), int(cy + radius) + 1):
        for x in range(int(cx - radius), int(cx + radius) + 1):
            dx, dy = x - cx, y - cy
            if dx * dx + dy * dy > radius * radius:
                continue
            shade = 1.0 - 0.12 * ((dx + dy) / (2 * radius) + 0.5)
            surface.blend(x, y, int(246 * shade), int(240 * shade), int(214 * shade), 255)
    # Craters: fixed offsets, so re-rendering does not move them.
    for ox, oy, r in ((-0.22, -0.16, 0.19), (0.16, 0.22, 0.13), (0.30, -0.30, 0.10)):
        ccx, ccy = cx + ox * radius, cy + oy * radius
        cr = r * radius
        for y in range(int(ccy - cr), int(ccy + cr) + 1):
            for x in range(int(ccx - cr), int(ccx + cr) + 1):
                dx, dy = x - ccx, y - ccy
                if dx * dx + dy * dy > cr * cr:
                    continue
                surface.blend(x, y, 206, 198, 176, 120)


def stars(surface, rng, count):
    for _ in range(count):
        x = rng.uniform(0, surface.width)
        y = rng.uniform(0, surface.height * 0.7)
        brightness = rng.uniform(0.25, 1.0)
        radius = rng.uniform(0.6, 1.7)
        surface.radial(x, y, radius * 2.4, (235, 238, 255),
                       brightness * rng.uniform(0.5, 1.0))
        surface.blend(int(x), int(y), 245, 248, 255, int(230 * brightness))


# ---------------------------------------------------------------------------
# The two packages
# ---------------------------------------------------------------------------
NEON_WINDOWS = [(53, 240, 224), (255, 63, 176), (255, 194, 74), (108, 255, 178)]
NEON_BODIES = [(11, 13, 24), (16, 16, 32), (8, 10, 20), (20, 18, 38)]


def neon_city_background(width, height, rng):
    surface = Surface(width, height)
    skyline(surface, rng, horizon=height * 0.86, palette=NEON_BODIES,
            window_palette=NEON_WINDOWS)
    return surface


def neon_city_glow(width, height, rng):
    """The lit skyline itself, with bloom, and a magenta wash above the roofs."""
    surface = Surface(width, height)
    horizon = height * 0.84
    x = -rng.randint(0, 40)
    while x < width:
        building_w = rng.randint(52, 124)
        building_h = rng.randint(int(horizon * 0.16), int(horizon * 0.92))
        top = horizon - building_h
        silhouette = bytes((9, 11, 22, 255))
        for yy in range(int(top), height):
            row = yy * width * 4
            x0, x1 = max(0, x), min(width, x + building_w)
            surface.px[row + x0 * 4:row + x1 * 4] = silhouette * (x1 - x0)
        cell_w, cell_h = 9, 13
        for wy in range(int(top) + 8, height - 6, cell_h):
            for wx in range(x + 6, x + building_w - 6, cell_w):
                if rng.random() > 0.40:
                    continue
                colour = rng.choice(NEON_WINDOWS)
                dim = rng.uniform(0.45, 1.0)
                lit = tuple(int(c * dim) for c in colour)
                for dy in range(min(5, cell_h - 4)):
                    for dx in range(min(4, cell_w - 3)):
                        surface.blend(wx + dx, wy + dy, *lit, 238)
        x += building_w + rng.randint(2, 10)
    surface.bloom(scale=5, strength=0.85)
    # Neon bounce light on the "wet street" band at the very bottom.
    for y in range(int(height * 0.94), height):
        for x2 in range(width):
            surface.blend(x2, y, 48, 120, 190, 26)
    return surface


def neon_haze(width, height, rng):
    surface = Surface(width, height)
    soft_bands(surface, rng, bands=5, colour=(196, 96, 190), alpha=46,
               y_range=(height * 0.55, height * 0.92), height_scale=(26, 74))
    return surface


def neon_rain(width, height, rng, near):
    surface = Surface(width, height)
    if near:
        rain(surface, rng, count=1500, length=96, alpha=132, thickness=2,
             tint=(196, 220, 255))
    else:
        rain(surface, rng, count=700, length=54, alpha=62, thickness=1,
             tint=(150, 176, 226))
    return surface


def mystic_background(width, height, rng):
    surface = Surface(width, height)
    surface.fill_gradient((6, 9, 24), (14, 22, 46))
    stars(surface, rng, count=420)
    return surface


def mystic_moon(width, height, rng):
    surface = Surface(width, height)
    moon(surface, cx=width * 0.66, cy=height * 0.24, radius=height * 0.105)
    return surface


def mystic_water(width, height, rng):
    surface = Surface(width, height)
    # Shimmer: horizontal bands whose brightness wobbles on a slow sine, so the
    # water reads as moving without any per-pixel noise to alias.
    for y in range(int(height * 0.60), height):
        depth = (y - height * 0.60) / (height * 0.40)
        for x in range(width):
            wave = (math.sin(x * 0.021 + y * 0.10) * 0.5 + 0.5) * \
                   (math.sin(y * 0.42) * 0.5 + 0.5)
            alpha = int(64 * (0.25 + 0.75 * wave) * (0.35 + 0.65 * depth))
            surface.blend(x, y, 120, 168, 226, alpha)
    return surface


def mystic_fog(width, height, rng):
    surface = Surface(width, height)
    soft_bands(surface, rng, bands=7, colour=(206, 216, 240), alpha=40,
               y_range=(height * 0.52, height * 0.95), height_scale=(34, 88))
    return surface


def mystic_fireflies(width, height, rng):
    surface = Surface(width, height)
    fireflies(surface, rng, count=110)
    return surface


LAYER_PLANS = {
    "NeonCity": [
        ("assets/background.jpg", "jpg", 1672, 941, neon_city_background, 0x4E31),
        ("assets/city_glow.png", "png", 1672, 941, neon_city_glow, 0x4E32),
        ("assets/haze.png", "png", 1692, 945, neon_haze, 0x4E33),
        ("assets/rain_2.png", "png", 1696, 1000,
         lambda w, h, rng: neon_rain(w, h, rng, near=False), 0x4E34),
        ("assets/rain_1.png", "png", 1708, 1040,
         lambda w, h, rng: neon_rain(w, h, rng, near=True), 0x4E35),
    ],
    "MysticMoon": [
        ("assets/background.jpg", "jpg", 1672, 941, mystic_background, 0x4D31),
        ("assets/moon_glow.png", "png", 1678, 945, mystic_moon, 0x4D32),
        ("assets/water_glow.png", "png", 1682, 941, mystic_water, 0x4D33),
        ("assets/fog.png", "png", 1712, 949, mystic_fog, 0x4D34),
        ("assets/fireflies.png", "png", 1684, 949, mystic_fireflies, 0x4D35),
    ],
}


def render(plan):
    """Render every file of a package, returning the manifest of what was made."""
    entries = []
    for relative, kind, width, height, maker, seed in plan:
        rng = random.Random(seed)
        surface = maker(width, height, rng)
        if kind == "jpg":
            entries.append({
                "file": relative, "kind": "jpg", "width": width, "height": height,
                "surface": surface,
            })
        else:
            entries.append({
                "file": relative, "kind": "png", "width": width, "height": height,
                "surface": surface,
            })
    return entries


def write_package(package_root, plan, dry_run):
    """Render and write one package, returning what it wrote.

    Every file it writes is read back and checked for the size it was asked for.
    Not paranoia: the JPEG path goes through an external converter (PIL or sips),
    and a converter that quietly resampled or fell back to another format would
    otherwise be discovered by a user on a desktop, not by this script.
    """
    written = []
    for entry in render(plan):
        target = package_root / entry["file"]
        if dry_run:
            print("  %-26s %4dx%-4d  (dry run:加 --write 才落盘)"
                  % (entry["file"], entry["width"], entry["height"]))
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        if entry["kind"] == "jpg":
            write_jpeg(target, entry["width"], entry["height"],
                       entry["surface"].to_rgb())
        else:
            write_png(target, entry["width"], entry["height"], entry["surface"].px)
        size = (read_jpeg_size(target) if entry["kind"] == "jpg" else read_png_size(target))
        if size != (entry["width"], entry["height"]):
            raise SystemExit("❌ %s 写出来是 %s,应为 %s —— 转换器不诚实"
                             % (target, size, (entry["width"], entry["height"])))
        digest = hashlib.sha256(target.read_bytes()).hexdigest()
        written.append({
            "file": entry["file"],
            "bytes": target.stat().st_size,
            "width": entry["width"],
            "height": entry["height"],
            "sha256": digest,
        })
        print("  %-26s %4dx%-4d %8d B  %s"
              % (entry["file"], entry["width"], entry["height"],
                 written[-1]["bytes"], digest[:12]))
    return written


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--package", choices=list(LAYER_PLANS) + ["all"], default="all")
    ap.add_argument("--write", action="store_true", help="写入 assets/")
    ap.add_argument("--check", action="store_true",
                    help="只比对:重新渲染并与磁盘上文件的 sha256 比较,不一致则非零退出")
    args = ap.parse_args()
    packages = list(LAYER_PLANS) if args.package == "all" else [args.package]

    for name in packages:
        print(name)
        plan = LAYER_PLANS[name]
        # Sizes are asserted against scene.ini below, not taken from this table
        # alone — a .ini edit that changes a layer box must fail loudly here.
        import configparser
        ini = configparser.ConfigParser()
        package_root = WALLPAPERS / (name + ".mdwall")
        scene_ini = package_root / "scene.ini"
        # read_string, not read(). configparser.read() silently ignores a file it
        # cannot open and returns the list of the ones it did read, so a wrong path
        # here produces an empty layer list — which then looks exactly like "this
        # package's scene.ini declares no layers". A loud failure is the only useful
        # one; the first version of this script did it the silent way.
        ini.read_string(scene_ini.read_text(encoding="utf-8"), source=str(scene_ini))
        declared = {dict(ini[section])["file"].replace("\\", "/"): section
                    for section in ini.sections() if section.startswith("Layer")}
        for relative, kind, width, height, maker, seed in plan:
            if relative not in declared:
                raise SystemExit("❌ %s 在 scene.ini 里没有对应图层:%s" % (name, relative))
            section = dict(ini[declared[relative]])
            want = (int(float(section["width"])), int(float(section["height"])))
            if want != (width, height):
                raise SystemExit(
                    "❌ %s 的 %s 尺寸是 %s,本脚本按 %s 渲染。"
                    "scene.ini 是图层盒子的唯一来源 —— 先改脚本对应的表格,再重新生成。"
                    % (name, relative, want, (width, height)))

        if args.check:
            ok = True
            encoders = []
            for entry in render(plan):
                target = package_root / entry["file"]
                if not target.exists():
                    print("    ❌ 缺 %s" % entry["file"])
                    ok = False
                    continue
                digest = hashlib.sha256(target.read_bytes()).hexdigest()
                # A committed file is only "the same art" if re-rendering reproduces
                # it. Comparing dimensions alone would let a silently different
                # image through, which is exactly the failure this script exists to
                # make impossible.
                if entry["kind"] == "jpg":
                    regenerated, converter = _jpeg_bytes(entry)
                    regenerated = hashlib.sha256(regenerated).hexdigest()
                    if converter not in encoders:
                        encoders.append(converter)
                else:
                    regenerated = hashlib.sha256(_png_bytes(entry)).hexdigest()
                if digest != regenerated:
                    print("    ❌ %s 与重新渲染的结果不一致(磁盘 %s / 重渲 %s)"
                          % (entry["file"], digest[:12], regenerated[:12]))
                    ok = False
            if not ok:
                sys.exit("❌ %s 的美术资产与脚本产物不一致" % name)
            # The encoder identity is part of the result, not decoration: a JPEG
            # mismatch means either the art changed or the encoder did, and only
            # this line tells the two apart.
            print("    ✅ 与重新渲染逐字节一致(jpeg 编码器:%s)"
                  % " + ".join(encoders) if encoders else "")
            print("      encoder: %s" % _jpeg_encoder_id())
        else:
            write_package(package_root, plan, dry_run=not args.write)


def _png_bytes(entry):
    """Re-render one PNG layer into memory so --check can hash what the script
    *would* write, without touching the working tree."""
    buffer = io.BytesIO()
    write_png(_FakePath(buffer), entry["width"], entry["height"], entry["surface"].px)
    return buffer.getvalue()


def _jpeg_encoder_id():
    """Name the encoder that will produce the comparison bytes.

    --check compares the digest of a re-encode, so its answer is only meaningful
    for the encoder that produced the committed file in the first place. PIL's
    own version *and* the libjpeg it was built against both change the emitted
    bytes at identical quality. So a PIL upgrade surfaces as a mismatch on art
    nobody touched — a gate that cries wolf, which is worse than no gate,
    because people learn to stop believing it. Printing the identity next to
    the result makes that case attributable in one look instead of a bisect.
    """
    try:
        import PIL
        from PIL import Image
    except ImportError:
        return "sips(macOS)"
    libjpeg = getattr(getattr(Image, "core", None), "jpeglib_version", "unknown")
    return "PIL %s / libjpeg %s" % (PIL.__version__, libjpeg)


def _jpeg_bytes(entry):
    """Same for a JPEG background, plus the encoder that made it.

    Returned as a pair because the caller has to print the encoder identity:
    see _jpeg_encoder_id. The encoder is deterministic for a given input and
    quality, so a committed file that came from this script hashes the same way
    twice — but only under the same encoder, which is exactly what that note is
    about.
    """
    buffer = io.BytesIO()
    converter = write_jpeg(_FakePath(buffer), entry["width"], entry["height"],
                           entry["surface"].to_rgb())
    return buffer.getvalue(), converter


class _FakePath:
    """Lets write_png / write_jpeg write into memory instead of to disk.

    Only the methods those two writers actually use are provided, so a caller
    cannot quietly start depending on a real path here."""

    def __init__(self, buffer):
        self._buffer = buffer

    def write_bytes(self, data):
        self._buffer.write(data)

    # PIL does NOT treat its `path` argument as a path. Image.save() calls
    # fp.fileno() first, and only when that raises AttributeError does it fall
    # back to using the object as a byte stream. So an in-memory target has to
    # offer write()/flush(), not just write_bytes().
    #
    # Until 2026-09-22 it did not, and the JPEG half of --check died with
    # `AttributeError: '_FakePath' object has no attribute 'write'`. The PNG
    # half went through write_bytes() and worked, so the one broken path was
    # also the one with no evidence at all — and at HEAD the script died before
    # reaching either, which is why this had never once run to completion.
    def write(self, data):
        self._buffer.write(data)

    def flush(self):
        pass

    def exists(self):
        return self._buffer.tell() > 0

    def with_suffix(self, _suffix):
        # Deliberately returns self: the sips fallback in write_jpeg cannot work
        # in memory (it shell out to a real path), so there is no temp .png to
        # hand back. PIL is the encoder for the in-memory path; if it were ever
        # missing, that is a loud failure here, not a silent wrong answer.
        return self

    def unlink(self, missing_ok=False):
        self._buffer.seek(0)
        self._buffer.truncate()


if __name__ == "__main__":
    main()
