param(
    [Parameter(Mandatory = $true)][string]$BuildOutput,
    [Parameter(Mandatory = $true)][string]$Destination,
    [Parameter(Mandatory = $true)][ValidateSet('arm64','x64')][string]$Architecture
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
$RepoRoot = Split-Path $PSScriptRoot -Parent

function Assert-File([string]$Root, [string]$Relative) {
    $path = Join-Path $Root $Relative
    if (-not (Test-Path $path -PathType Leaf)) {
        throw "Full test package is missing: $Relative"
    }
}

New-Item -ItemType Directory -Force -Path $Destination | Out-Null
foreach ($exe in @('MiaoDesk.exe','MiaoDeskWallpaper.exe','MiaoDeskHarness.exe')) {
    Assert-File $BuildOutput $exe
    Copy-Item (Join-Path $BuildOutput $exe) $Destination -Force
}
Get-ChildItem $BuildOutput -Filter '*.dll' -File -ErrorAction SilentlyContinue |
    Copy-Item -Destination $Destination -Force

& (Join-Path $PSScriptRoot 'prepare-store-runtime.ps1') -DeployDir $Destination -Architecture $Architecture
if ($LASTEXITCODE -ne 0) { throw "Runtime materialization failed with exit code $LASTEXITCODE" }

$wallpapersSource = Join-Path $RepoRoot 'assets\wallpapers'
$wallpapersDestination = Join-Path $Destination 'Wallpapers'
New-Item -ItemType Directory -Force -Path $wallpapersDestination | Out-Null
Copy-Item (Join-Path $wallpapersSource '*') $wallpapersDestination -Recurse -Force

$required = @(
    'MiaoDesk.exe',
    'MiaoDeskWallpaper.exe',
    'MiaoDeskHarness.exe',
    'Runtime\Node\node.exe',
    'Runtime\Node\node_modules\@deepseek-ai\dsh\lib\bin.js',
    'Pi\node_modules\@earendil-works\pi-coding-agent\dist\cli.js',
    'Goz\goz.exe',
    'Goz\gozd.exe',
    'Wallpapers\MiaoCloud.mdwall\manifest.json',
    'Wallpapers\MiaoCloud.mdwall\scene.ini',
    'Wallpapers\MiaoCloud.mdwall\assets\background.jpg',
    'Wallpapers\MiaoCloud.mdwall\assets\cat.png',
    'Wallpapers\MiaoCloud.mdwall\assets\tail.png',
    'Wallpapers\MiaoCloud.mdwall\assets\blink.png',
    'Wallpapers\NeonCity.mdwall\manifest.json',
    'Wallpapers\NeonCity.mdwall\scene.ini',
    'Wallpapers\MysticMoon.mdwall\manifest.json',
    'Wallpapers\MysticMoon.mdwall\scene.ini'
)
foreach ($relative in $required) { Assert-File $Destination $relative }

# Guard against accidentally packaging Git LFS pointer files as wallpaper images.
foreach ($relative in @(
    'Wallpapers\MiaoCloud.mdwall\assets\background.jpg',
    'Wallpapers\MiaoCloud.mdwall\assets\cat.png',
    'Wallpapers\MiaoCloud.mdwall\assets\tail.png',
    'Wallpapers\MiaoCloud.mdwall\assets\blink.png'
)) {
    $path = Join-Path $Destination $relative
    if ((Get-Item $path).Length -lt 1024) { throw "Wallpaper image still looks like an LFS pointer: $relative" }
}

Set-Content -Path (Join-Path $Destination 'FULL-TEST-COMPONENTS.txt') -Encoding UTF8 -Value @(
    "Architecture: $Architecture"
    'MiaoDesk native shell/search/settings'
    'MiaoDeskWallpaper desktop engine'
    'MiaoDeskHarness workbench host'
    'Shared portable Node runtime'
    'DeepSeek Harness dsh production dependencies'
    'Pi Agent production dependencies'
    'goz + gozd native file search runtime'
    'MiaoCloud / NeonCity / MysticMoon wallpaper packages'
    'Windows Store icon assets are generated by build-msix.ps1'
)

Write-Host "Complete $Architecture test package staging is ready: $Destination" -ForegroundColor Green
